### ISSUE TITLE
Tooltips are in Chinese/Japanese...

### ISSUE THREAD

**Issue by NeilAllen** [wecatch/ember-cli-simditor#3]
... what's to do?

**Comment by NeilAllen** [comment]
I've found `Module.locale = 'zh-CN';` and changed it to `Module.locale = 'en-US';`

in bower_components/simple-module/lib/module.js. What do I have to do to this change being lost when I update the addon?

**Comment by jeanlouispy** [comment]
Hi, 
You can set this value directly in your JavaScript code before instantiate the editor.

`
Simditor.locale = 'en-US';


editor = new Simditor({
           textarea: $('#editor'),          
        });
`

**Comment by yunusbek1710** [comment]
i'm understand.
