### ISSUE TITLE
please explain...

### ISSUE THREAD

**Issue by NeilAllen** [wecatch/ember-cli-simditor#4]
...editor=(mut editor) }}

What use is it/how would I use it?

**Comment by zhyq0826** [comment]
@NeilAllen  Go to see Emberjs doc http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_mut, this doc has explained in more detail。：）

In a word, with 'mut' helper,  you can get editor instance reference outside the component.

**Comment by NeilAllen** [comment]
Hi!, thanks for a reply.

I've had a look & indeed used **mut** for updating values, but I'm struggling. I'm looking to create acceptance test using **ember-cli-page-objec**t; if I use **setValue()** and **sync()**I can see the text on the page but it doesn't get through to the underlying variable.

Any clues?

**Comment by zhyq0826** [comment]
@NeilAllen I don't have any clues :). You can go https://embercommunity.slack.com to get help.
